using System.Collections.Generic;

namespace ML.Utils.DataFeed.DiscountWatchStore
{
    public partial class DiscountWatchStoreManager
    {
        public const string RootUrl = "http://www.discountwatchstore.com";

        #region Brands

        public static readonly Brands Brands = new Brands
        {
            new Brand("Alpina"),
            new Brand("Anne Klein"),
            new Brand("Antonio Banderas", "AB"),
            new Brand("Armourlite"),
            new Brand("Banda"),
            new Brand("Bering"),
            new Brand("Bertucci"),
            new Brand("Betsey Johnson"),
            new Brand("Braun"),
            new Brand("Brentwood"),
            new Brand("Bulova"),
            new Brand("Burberry"),
            new Brand("Bvlgari"),
            new Brand("Calvin Klein", "CK"),
            new Brand("Caran D'Ache"),
            new Brand("Caravelle", "Caravelle New York"),
            new Brand("Carolina Herrera", "CH"),
            new Brand("Carrera"),
            new Brand("Cartier"),
            new Brand("Casio"),
            new Brand("Chopard"),
            new Brand("Citizen"),
            new Brand("Converse"),
            new Brand("Daniel Wellington"),
            new Brand("Davidoff"),
            new Brand("Debeer"),
            new Brand("Diesel"),
            new Brand("Discount Watch Store"),
            new Brand("DKNY"),
            new Brand("Dolce & Gabbana", "Dolce Gabbana", "DG"),
            new Brand("ESQ"),
            new Brand("Fendi"),
            new Brand("Ferragamo"),
            new Brand("Ferrari"),
            new Brand("Festina"),
            new Brand("Fossil"),
            new Brand("Frederique Constant"),
            new Brand("Freestyle"),
            new Brand("Gianni Versace", "Versace"),
            new Brand("Giorgio Armani", "GA"),
            new Brand("Givenchy"),
            new Brand("Gucci"),
            new Brand("Guerlain"),
            new Brand("Guess"),
            new Brand("H3 Tactical"),
            new Brand("Hadley Roma"),
            new Brand("Hamilton"),
            new Brand("Harley Davidson"),
            new Brand("Hirsch"),
            new Brand("Hugo Boss"),
            new Brand("I.W. Suisse"),
            new Brand("Ice-Watch", "Ice"),
            new Brand("Invicta"),
            new Brand("Jean Paul Gaultier", "JP Gaultier"),
            new Brand("Jorg Gray"),
            new Brand("Juicy Couture"),
            new Brand("Karl Lagerfeld"),
            new Brand("Kate Spade"),
            new Brand("Kenneth Cole"),
            new Brand("Kenzo"),
            new Brand("Kipling"),
            new Brand("Komono"),
            new Brand("Lacoste"),
            new Brand("Lamy"),
            new Brand("Lancome Eau De", "Lancome"),
            new Brand("L'instant De Guerlain", "Guerlain L'Instant"),
            new Brand("Luminox"),
            new Brand("Marc by Marc Jacobs", "Marc Jacobs"),
            new Brand("Maserati"),
            new Brand("Maui Jim"),
            new Brand("Michael Kors"),
            new Brand("Mido"),
            new Brand("Miu Miu"),
            new Brand("Momentus"),
            new Brand("Mondaine"),
            new Brand("Mont Blanc", "Montblanc"),
            new Brand("Movado"),
            new Brand("Nathan"),
            new Brand("Nixon"),
            new Brand("Oakley"),
            new Brand("Oniss"),
            new Brand("Orefici"),
            new Brand("Orient"),
            new Brand("Paco Rabanne"),
            new Brand("Police"),
            new Brand("Projects"),
            new Brand("Pulsar"),
            new Brand("Ralph Lauren", "RL"),
            new Brand("Ray Ban", "Ray-Ban"),
            new Brand("Raymond Weil"),
            new Brand("S. Coifman"),
            new Brand("Seiko"),
            new Brand("Skagen"),
            new Brand("Soleus"),
            new Brand("Speedo"),
            new Brand("Strumento Marino"),
            new Brand("Suunto"),
            new Brand("Swatch"),
            new Brand("Swiss Army"),
            new Brand("Szanto"),
            new Brand("Technomarine"),
            new Brand("Thierry Mugler"),
            new Brand("Timberland"),
            new Brand("Timex"),
            new Brand("Tissot"),
            new Brand("Tom Ford"),
            new Brand("Tommy Hilfiger"),
            new Brand("Toscana"),
            new Brand("Toy"),
            new Brand("Traser"),
            new Brand("TW Steel"),
            new Brand("Welder"),
            new Brand("Wenger"),
            new Brand("Wittnauer"),
            new Brand("Yves Saint Laurent", "YSL"),
            new Brand("Zippo"),
        };

        #endregion

        #region DataFeeds

        public static readonly List<DataFeed> DataFeeds = new List<DataFeed>
        {
            //Watch
            new DataFeed(ProductType.Watch, "alpina", Brands["Alpina"], "Watches"),
            new DataFeed(ProductType.Watch, "welder", Brands["Welder"], "Watches"),
            new DataFeed(ProductType.Watch, "Anne-Klein-Watches_c_1240.html", Brands["Anne Klein"], "Watches"),
            new DataFeed(ProductType.Watch, "Armourlite-Watches_c_3197.html", Brands["Armourlite"], "Watches"),
            new DataFeed(ProductType.Watch, "bering", Brands["Bering"], "Watches"),
            new DataFeed(ProductType.Watch, "bertucci", Brands["Bertucci"], "Watches"),
            new DataFeed(ProductType.Watch, "Betsey-Johnson-Watches_c_3195.html", Brands["Betsey Johnson"], "Watches"),
            new DataFeed(ProductType.Watch, "braun", Brands["Braun"], "Watches"),
            new DataFeed(ProductType.Watch, "Bulova-Watches_c_41.html", Brands["Bulova"], "Watches"),
            new DataFeed(ProductType.Watch, "Burberry-Watches_c_3188.html", Brands["Burberry"], "Watches"),
            new DataFeed(ProductType.Watch, "Calvin-Klein-Watches_c_1242.html", Brands["Calvin Klein"], "Watches"),
            new DataFeed(ProductType.Watch, "Caravelle-Watches_c_3096.html", Brands["Caravelle"], "Watches"),
            new DataFeed(ProductType.Watch, "caravelle-new-york", Brands["Caravelle New York"], "Watches"),
            new DataFeed(ProductType.Watch, "Casio-Watches_c_44.html", Brands["Casio"], "Watches"),
            new DataFeed(ProductType.Watch, "Citizen-Watches_c_45.html", Brands["Citizen"], "Watches"),
            new DataFeed(ProductType.Watch, "Converse-Watches_c_1361.html", Brands["Converse"], "Watches"),
            new DataFeed(ProductType.Watch, "Daniel-Wellington-Watches_c_3186.html", Brands["Daniel Wellington"], "Watches"),
            new DataFeed(ProductType.Watch, "Diesel-Watches_c_1241.html", Brands["Diesel"], "Watches"),
            new DataFeed(ProductType.Watch, "DKNY-Watches_c_718.html", Brands["DKNY"], "Watches"),
            new DataFeed(ProductType.Watch, "Dolce-Gabbana-Watches_c_79.html", Brands["Dolce & Gabbana"], "Watches"),
            new DataFeed(ProductType.Watch, "ESQ-Watches_c_3198.html", Brands["ESQ"], "Watches"),
            new DataFeed(ProductType.Watch, "Ferrari-Watches_c_3194.html", Brands["Ferrari"], "Watches"),
            new DataFeed(ProductType.Watch, "Festina-Watches_c_83.html", Brands["Festina"], "Watches"),
            new DataFeed(ProductType.Watch, "Fossil-Watches_c_716.html", Brands["Fossil"], "Watches"),
            new DataFeed(ProductType.Watch, "frederique-constant", Brands["Frederique Constant"], "Watches"),
            new DataFeed(ProductType.Watch, "Freestyle-Watches_c_1304.html", Brands["Freestyle"], "Watches"),
            new DataFeed(ProductType.Watch, "Gucci-Watches_c_1198.html", Brands["Gucci"], "Watches"),
            new DataFeed(ProductType.Watch, "Guess-Watches_c_2933.html", Brands["Guess"], "Watches"),
            new DataFeed(ProductType.Watch, "H3-Tactical-Watches_c_516.html", Brands["H3 Tactical"], "Watches"),
            new DataFeed(ProductType.Watch, "Hamilton-Watches_c_591.html", Brands["Hamilton"], "Watches"),
            new DataFeed(ProductType.Watch, "harley-davidson", Brands["Harley Davidson"], "Watches"),
            new DataFeed(ProductType.Watch, "Hugo-Boss-Watches_c_1252.html", Brands["Hugo Boss"], "Watches"),
            new DataFeed(ProductType.Watch, "Ice-Watch-Watches_c_1173.html", Brands["Ice-Watch"], "Watches"),
            new DataFeed(ProductType.Watch, "Invicta-Watches_c_86.html", Brands["Invicta"], "Watches"),
            new DataFeed(ProductType.Watch, "Jorg-Gray-Watches_c_696.html", Brands["Jorg Gray"], "Watches"),
            new DataFeed(ProductType.Watch, "Juicy-Couture-Watches_c_3093.html", Brands["Juicy Couture"], "Watches"),
            new DataFeed(ProductType.Watch, "Karl-Lagerfeld-Watches_c_3146.html", Brands["Karl Lagerfeld"], "Watches"),
            new DataFeed(ProductType.Watch, "Kate-Spade-Watches_c_3200.html", Brands["Kate Spade"], "Watches"),
            new DataFeed(ProductType.Watch, "Kenneth-Cole-Watches_c_1188.html", Brands["Kenneth Cole"], "Watches"),
            new DataFeed(ProductType.Watch, "komono", Brands["Komono"], "Watches"),
            new DataFeed(ProductType.Watch, "Lacoste-Watches_c_1315.html", Brands["Lacoste"], "Watches"),
            new DataFeed(ProductType.Watch, "Luminox-Watches_c_108.html", Brands["Luminox"], "Watches"),
            new DataFeed(ProductType.Watch, "Marc-by-Marc-Jacobs-Watches_c_1209.html", Brands["Marc by Marc Jacobs"], "Watches"),
            new DataFeed(ProductType.Watch, "maserati", Brands["Maserati"], "Watches"),
            new DataFeed(ProductType.Watch, "Michael-Kors-Watches_c_496.html", Brands["Michael Kors"], "Watches"),
            new DataFeed(ProductType.Watch, "mido", Brands["Mido"], "Watches"),
            new DataFeed(ProductType.Watch, "momentus", Brands["Momentus"], "Watches"),
            new DataFeed(ProductType.Watch, "Mondaine-Watches_c_14.html", Brands["Mondaine"], "Watches"),
            new DataFeed(ProductType.Watch, "Movado-Watches_c_3097.html", Brands["Movado"], "Watches"),
            new DataFeed(ProductType.Watch, "Nixon-Watches_c_1202.html", Brands["Nixon"], "Watches"),
            new DataFeed(ProductType.Watch, "Oniss-Watches_c_129.html", Brands["Oniss"], "Watches"),
            new DataFeed(ProductType.Watch, "orefici", Brands["Orefici"], "Watches"),
            new DataFeed(ProductType.Watch, "Orient-Watches_c_132.html", Brands["Orient"], "Watches"),
            new DataFeed(ProductType.Watch, "Police-Watches_c_1286.html", Brands["Police"], "Watches"),
            new DataFeed(ProductType.Watch, "projects", Brands["Projects"], "Watches"),
            new DataFeed(ProductType.Watch, "Pulsar-Watches_c_146.html", Brands["Pulsar"], "Watches"),
            new DataFeed(ProductType.Watch, "Raymond-Weil-Watches_c_3064.html", Brands["Raymond Weil"], "Watches"),
            new DataFeed(ProductType.Watch, "s-coifman", Brands["S. Coifman"], "Watches"),
            new DataFeed(ProductType.Watch, "Seiko-Watches_c_156.html", Brands["Seiko"], "Watches"),
            new DataFeed(ProductType.Watch, "Skagen-Watches_c_1151.html", Brands["Skagen"], "Watches"),
            new DataFeed(ProductType.Watch, "Soleus-Watches_c_1293.html", Brands["Soleus"], "Watches"),
            new DataFeed(ProductType.Watch, "Speedo-Watches_c_2977.html", Brands["Speedo"], "Watches"),
            new DataFeed(ProductType.Watch, "Suunto-Watches_c_3095.html", Brands["Suunto"], "Watches"),
            new DataFeed(ProductType.Watch, "strumento-marino", Brands["Strumento Marino"], "Watches"),
            new DataFeed(ProductType.Watch, "Swatch-Watches_c_1204.html", Brands["Swatch"], "Watches"),
            new DataFeed(ProductType.Watch, "Swiss-Army-Watches_c_429.html", Brands["Swiss Army"], "Watches"),
            new DataFeed(ProductType.Watch, "Szanto-Watches_c_3199.html", Brands["Szanto"], "Watches"),
            new DataFeed(ProductType.Watch, "Timberland-Watches_c_3145.html", Brands["Timberland"], "Watches"),
            new DataFeed(ProductType.Watch, "Timex-Watches_c_1070.html", Brands["Timex"], "Watches"),
            new DataFeed(ProductType.Watch, "Tommy-Hilfiger-Watches_c_2978.html", Brands["Tommy Hilfiger"], "Watches"),
            new DataFeed(ProductType.Watch, "Toy-Watches_c_1101.html", Brands["Toy"], "Watches"),
            new DataFeed(ProductType.Watch, "Traser-Watches_c_579.html", Brands["Traser"], "Watches"),
            new DataFeed(ProductType.Watch, "TW-Steel-Watches_c_180.html", Brands["TW Steel"], "Watches"),
            new DataFeed(ProductType.Watch, "Wenger-Watches_c_181.html", Brands["Wenger"], "Watches"),
            new DataFeed(ProductType.Watch, "Wittnauer-Watches_c_2914.html", Brands["Wittnauer"], "Watches"),
            new DataFeed(ProductType.Watch, "Technomarine-Watches_c_2916.html", Brands["Technomarine"], "Watches"),

            //HandbagWallet
            new DataFeed(ProductType.HandbagWallet, "Kate-Spade_c_3147.html", Brands["Kate Spade"], "Handbags & Wallets"),
            new DataFeed(ProductType.HandbagWallet, "Kipling_c_3190.html", Brands["Kipling"], "Handbags & Wallets"),
            new DataFeed(ProductType.HandbagWallet, "Michael-Kors_c_3065.html", Brands["Michael Kors"], "Handbags & Wallets"),

            //Sunglass
            new DataFeed(ProductType.Sunglass, "Carrera_c_1217.html", Brands["Carrera"], "Sunglasses"),
            new DataFeed(ProductType.Sunglass, "Fendi_c_1191.html", Brands["Fendi"], "Sunglasses"),
            new DataFeed(ProductType.Sunglass, "Gucci_c_1218.html", Brands["Gucci"], "Sunglasses"),
            new DataFeed(ProductType.Sunglass, "Marc-by-Marc-Jacobs_c_2966.html", Brands["Marc by Marc Jacobs"], "Sunglasses"),
            new DataFeed(ProductType.Sunglass, "Maui-Jim_c_3125.html", Brands["Maui Jim"], "Sunglasses"),
            new DataFeed(ProductType.Sunglass, "Michael-Kors_c_1190.html", Brands["Michael Kors"], "Sunglasses"),
            new DataFeed(ProductType.Sunglass, "miu-miu", Brands["Miu Miu"], "Sunglasses"),
            new DataFeed(ProductType.Sunglass, "oakley", Brands["Oakley"], "Sunglasses"),
            new DataFeed(ProductType.Sunglass, "Ray-Ban_c_1185.html", Brands["Ray Ban"], "Sunglasses"),
            new DataFeed(ProductType.Sunglass, "Tom-Ford_c_2980.html", Brands["Tom Ford"], "Sunglasses"),

            //Accessory
            new DataFeed(ProductType.Perfume, "Perfumes_c_2692.html", null, "Accessories"),
            new DataFeed(ProductType.Perfume, "GIVENCHY_c_2996.html", Brands["Givenchy"], "Accessories"),
            new DataFeed(ProductType.Clock, "Clocks_c_2909.html", null, "Accessories"),
            new DataFeed(ProductType.RunningAccessory, "Running-Accessories_c_2643.html", null, "Accessories"),
            new DataFeed(ProductType.SwissAmryKnives, "Swiss-Army-Knives_c_1210.html", Brands["Swiss Army"], "Accessories"),
            new DataFeed(ProductType.WatchAccessory, "Watch-Accessories", null, "Accessories"),
            new DataFeed(ProductType.WatchBand, "Watch-Bands_c_10.html", null, "Accessories"),
            new DataFeed(ProductType.WritingInstrument, "Pens_c_1254.html", null, "Accessories"),
            new DataFeed(ProductType.ZippoLighter, "Zippo-Lighters_c_1276.html", null, "Accessories"),

            //Misc
            new DataFeed(ProductType.UnknownMisc, "Misc", null, "Misc"),

            //New Arrivals
            new DataFeed(ProductType.UnknownNewArrivals, "New-Arrivals_c_1004.html", null, "New Arrivals"),
        };

        #endregion
    }
}
